# Generated by Django 5.2.17 on 2026-08-27 01:54

import django.db.models.deletion
import transmissao.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('codigo_convite', models.CharField(default=transmissao.models.generate_invite_code, editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('transmitindo', 'Transmitindo'), ('encerrada', 'Encerrada')], default='aguardando', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_proprietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_sala', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='transmissao.sala')),
            ],
            options={
                'verbose_name': 'participante da sala',
                'verbose_name_plural': 'participantes da sala',
                'ordering': ['joined_at'],
                'constraints': [models.UniqueConstraint(fields=('sala', 'usuario'), name='unique_participante_por_sala')],
            },
        ),
    ]
